name: Deploy
on:
  push:
    branches:
      - 'actions-testing'
    paths:
      - 'lambdas/**'
      - 'smoothie/**'
      - 'app.py'
      - 'requirements.txt'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IS_PROD: true
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: cdk deploy
        uses: scottbrenner/aws-cdk-action@master
        with:
          args: 'deploy SmoothieStackProd --require-approval never'