name: Deploy
on:
  push:
    branches:
      - 'actions-testing'
    paths:
      - 'lambdas/**'
      - 'smoothie/**'
      - 'app.py'
      - 'requirements.txt'
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      IS_PROD: true
    steps:
      - uses: actions/checkout@v2
      
      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: 'deploy'
          cdk_version: '1.125.0'
          cdk_stack: 'SmoothieStackProd'
          actions_comment: false